settings:
  progress_bar_width: 10
  progress_bar_yes: "&d"
  progress_bar_no: "&8"
  progress_bar_symbol: "∎"

database:
  jdbc-url: "jdbc:mysql://localhost:3306/treasures"
  username: "root"
  password: ""
