name: Treasures
version: "${version}"
main: ru.nilsson03.treasures.TreasuresPlugin
api-version: "1.16"
author: nilsson03
depend:
  - BaseLibrary
  - DecentHolograms
  - Database-core
  - InvUIPlugin
commands:
  treasures:
    description: "Admin command"
    permission: treasures.admin
